### PR TITLE
Filter filename

### PR DESCRIPTION
**Pull request by Aisha-D**
Creates ped file with reported sex filtered from filename. Calculates predicted sex based on x_het calls. Inputs are an array of .somalier files.

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate/1)

### CODE REVIEW

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 2 of 8 files at r1, 4 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate/1)* status: all files reviewed, 15 unresolved discussions (waiting on @Aisha-D)

___
*[dxapp.json, line 11 at r3](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate/1#-MVUp05ZEjTIVhmDKYDW:-MVUp05ZEjTIVhmDKYDX:bcu9uq1) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate/blob/fe0cf285af8a945caa03b30c45d3ecce0ebae7c9/dxapp.json#L11)):*
> ```
> input_file
> ```
Could this be given a more meaningful name?

`input` is somewhat redundant since we are defining an input anyway. How about `somalier_extract_`instead, which would be more descriptive of what is required

It's an array of `_files`, not a single `_file`

So I would suggest `somalier_extract_files`
___
*[dxapp.json, line 21 at r3](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate/1#-MVUqkSD9RikcCkDmsu5:-MVUqkSD9RikcCkDmsu6:b-bd7cn) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate/blob/fe0cf285af8a945caa03b30c45d3ecce0ebae7c9/dxapp.json#L21)):*
> ```
>       "name": "f",
>       "label": "Female",
> ```
Maybe `female_threshold` / `Female threshold`?
___
*[dxapp.json, line 24 at r3](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate/1#-MVUqvOVEvalZb9T1Fju:-MVUqvOVEvalZb9T1Fjv:b-b0fyza) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate/blob/fe0cf285af8a945caa03b30c45d3ecce0ebae7c9/dxapp.json#L24)):*
> ```
> A integer value for het calls threshold for females. Default is 45
> ```
How is the threshold used? Is female assigned to samples above or below the threshsold?
___
*[dxapp.json, line 28 at r3](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate/1#-MVUr2VmD_4Ib0HuiYJU:-MVUr2VmD_4Ib0HuiYJV:bs9mqr6) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate/blob/fe0cf285af8a945caa03b30c45d3ecce0ebae7c9/dxapp.json#L28)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
>     {
>       "name": "m",
>       "label": "Male",
>       "class": "string",
>       "optional": true,
>       "help": "A integer value for het calls threshold for males. Default is 1"
>     }
> ```
</details>

See comments for female section
___
*[dxapp.json, line 41 at r3](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate/1#-MVUrDqT8--YuU9NXPTu:-MVUrDqT8--YuU9NXPTv:bi0ioqi) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate/blob/fe0cf285af8a945caa03b30c45d3ecce0ebae7c9/dxapp.json#L41)):*
> ```
>       "help": ""
> ```
Could we add a short description of the output files to each of the help fields?
___
*[dxapp.json, line 99 at r3](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate/1#-MVUrUnLCCXojRq4yHCY:-MVUrUnMD7xLyIroFmfi:b-ehuclk) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate/blob/fe0cf285af8a945caa03b30c45d3ecce0ebae7c9/dxapp.json#L99)):*
> ```
> "mem1_ssd1_v2_x4"
> ```
Has this instance type been tested for large numbers of input files?
___
*[README.md, line 4 at r3](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate/1#-MVUrhsE1n71qjxsUrkx:-MVUrhsE1n71qjxsUrky:bpuf1il) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate/blob/fe0cf285af8a945caa03b30c45d3ecce0ebae7c9/README.md#L4)):*
> ```
> Can also predict relatedness between samples and ancestry.
> ```
Is this info included in the output files?
___
*[README.md, line 11 at r3](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate/1#-MVUs0vT4CMsYhwRU2la:-MVUs0vT4CMsYhwRU2lb:b-ysw5av) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate/blob/fe0cf285af8a945caa03b30c45d3ecce0ebae7c9/README.md#L11)):*
> ```Markdown
> 
> ## What are the inputs?
> * Array of {sample}.somalier files
> ```

Could we describe where these come from (i.e. extract)
___
*[README.md, line 14 at r3](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate/1#-MVUsSiF0yT1Vxi1FxBx:-MVUsSiF0yT1Vxi1FxBy:b-mk32pi) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate/blob/fe0cf285af8a945caa03b30c45d3ecce0ebae7c9/README.md#L14)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> * Reported sex in xlsx file, defaults are labelled as unknown (Optional):
>   * Column 1 : Lab numbers
>   * Column 2 : Exome Numbers
>   * Column 3 : Reported Sex (Categorised as F and M)
> ```
</details>

What happens if you provide this file, and the filenames contain a sex which you extract? Which takes priority?
___
*[README.md, line 17 at r3](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate/1#-MVUsjAPA3aHsokZmsvU:-MVUsjAPA3aHsokZmsvV:bjemh47) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate/blob/fe0cf285af8a945caa03b30c45d3ecce0ebae7c9/README.md#L17)):*
> ```
> Text File which contains prefix for outputs, can be run folder here ideally, default is somalier prefix. (Optional)·
> ```
Does this need to be a file rather than a string containing the prefix? There may be a good reason for doing this in the way you have done it, but if so it would be useful to explain this
___
*[README.md, line 30 at r3](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate/1#-MVUt5FD0GcD8JJAmhOm:-MVUt5FD0GcD8JJAmhOn:b-h3z58a) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate/blob/fe0cf285af8a945caa03b30c45d3ecce0ebae7c9/README.md#L30)):*
> ```
> a multi workflow as the app can take multiple inputs in.
> ```
a multi sample workflow
___
*[README.md, line 34 at r3](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate/1#-MVUtK9X-dA861K3ViOz:-MVUtK9X-dA861K3ViP-:behcxdk) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate/blob/fe0cf285af8a945caa03b30c45d3ecce0ebae7c9/README.md#L34)):*
> ```
> Males typically have 0 or 1 het calls whereas female have a wider range, typically starting at 45.
> ```
Exact numbers will depend on the assay, I would describe this in more abstract terms rather than giving specific numbers
___
*[resources/home/dnanexus/make_ped.py, line 72 at r3](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate/1#-MVkN9sk-8esKWqQ4JcA:-MVkN9sm7Zrl8O3vbMCd:b-b6ic7u) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate/blob/fe0cf285af8a945caa03b30c45d3ecce0ebae7c9/resources/home/dnanexus/make_ped.py#L72)):*
> ```Python
>     samplesID = [sample.split("_")[0] for sample in samplesID]
> 
>     FamilyID = samplesID
> ```

Could we add a comment here to explain that you are preparing arrays of values for each of the fields in the df?
___
*[src/eggd_somalier_relate.sh, line 9 at r3](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate/1#-MVkNdaB93cBiLpQ6dTq:-MVkNdaCASuxKbC13Wij:bai20wc) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate/blob/fe0cf285af8a945caa03b30c45d3ecce0ebae7c9/src/eggd_somalier_relate.sh#L9)):*
> ```
>     echo "Value of female: '${f}'"
>     echo "Value of male: '${m}'"
> ```
female threshold
male threshold

might be clearer
___
*[src/eggd_somalier_relate.sh, line 16 at r3](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate/1#-MVkNqeMDChZInbwRAcx:-MVkNqeMDChZInbwRAcy:b-9vfzpm) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate/blob/fe0cf285af8a945caa03b30c45d3ecce0ebae7c9/src/eggd_somalier_relate.sh#L16)):*
> ```
> find ~/in -type f -name "*" -print0 | xargs -0 -I {} mv {} ./
> ```
Add a comment to explain this line please

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate/1)* status: 1 of 6 files reviewed, 15 unresolved discussions (waiting on @Aisha-D and @mattgarner)

___
*[dxapp.json, line 99 at r3](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate/1#-MVUrUnLCCXojRq4yHCY:-MW-2VA7C-fb5yslTkWa:bpfr9eh) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate/blob/fe0cf285af8a945caa03b30c45d3ecce0ebae7c9/dxapp.json#L99)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> "mem1_ssd1_v2_x4"
> ```
Has this instance type been tested for large numbers of input files?
</blockquote></details>

Yep, this instance was used when running ~200 samples. Took about 20mins.
___
*[README.md, line 4 at r3](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate/1#-MVUrhsE1n71qjxsUrkx:-MW-2zNB9cu-Tl9E1zRm:b-8khbzo) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate/blob/fe0cf285af8a945caa03b30c45d3ecce0ebae7c9/README.md#L4)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> Can also predict relatedness between samples and ancestry.
> ```
Is this info included in the output files?
</blockquote></details>

Ancestry is not - needs its own app so removed mention of ancestry in new version. Rephrased it to make more sense. 
___
*[README.md, line 14 at r3](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate/1#-MVUsSiF0yT1Vxi1FxBx:-MVzkTqy3tV5AVS9chuJ:ba0iqov) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate/blob/fe0cf285af8a945caa03b30c45d3ecce0ebae7c9/README.md#L14)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> * Reported sex in xlsx file, defaults are labelled as unknown (Optional):
>   * Column 1 : Lab numbers
>   * Column 2 : Exome Numbers
>   * Column 3 : Reported Sex (Categorised as F and M)
> ```
What happens if you provide this file, and the filenames contain a sex which you extract? Which takes priority?
</blockquote></details>

I thought I had updated the readme on this branch sorry! As reported sex is pulled from filename, I removed this input. Removed this now from readme.

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate/1)* status: 1 of 6 files reviewed, 15 unresolved discussions (waiting on @mattgarner)

___
*[dxapp.json, line 11 at r3](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate/1#-MVUp05ZEjTIVhmDKYDW:-MWPoH0c6PgVRuMrVuwD:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate/blob/fe0cf285af8a945caa03b30c45d3ecce0ebae7c9/dxapp.json#L11)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> input_file
> ```
Could this be given a more meaningful name?

`input` is somewhat redundant since we are defining an input anyway. How about `somalier_extract_`instead, which would be more descriptive of what is required

It's an array of `_files`, not a single `_file`

So I would suggest `somalier_extract_files`
</blockquote></details>

Done.
___
*[dxapp.json, line 21 at r3](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate/1#-MVUqkSD9RikcCkDmsu5:-MWPoJpG6RAqzofOD-nY:bkvte04) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate/blob/fe0cf285af8a945caa03b30c45d3ecce0ebae7c9/dxapp.json#L21)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
>       "name": "f",
>       "label": "Female",
> ```
Maybe `female_threshold` / `Female threshold`?
</blockquote></details>

Removed this input of Female and Male threshold for this app but included feedback on the relate2multiqc app
___
*[dxapp.json, line 24 at r3](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate/1#-MVUqvOVEvalZb9T1Fju:-MWPoge1BlRKF7RfhIjI:b-sfzktx) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate/blob/fe0cf285af8a945caa03b30c45d3ecce0ebae7c9/dxapp.json#L24)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> A integer value for het calls threshold for females. Default is 45
> ```
How is the threshold used? Is female assigned to samples above or below the threshsold?
</blockquote></details>

Above, explained this better in the readme of relate2multiqc app as threshold is irrelevant in this app.
___
*[dxapp.json, line 28 at r3](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate/1#-MVUr2VmD_4Ib0HuiYJU:-MWPoKCF0pCy-_pQCIIx:bkvte04) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate/blob/fe0cf285af8a945caa03b30c45d3ecce0ebae7c9/dxapp.json#L28)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
>     {
>       "name": "m",
>       "label": "Male",
>       "class": "string",
>       "optional": true,
>       "help": "A integer value for het calls threshold for males. Default is 1"
>     }
> ```
See comments for female section
</blockquote></details>

Removed this input of Female and Male threshold for this app but included feedback on the relate2multiqc app
___
*[dxapp.json, line 41 at r3](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate/1#-MVUrDqT8--YuU9NXPTu:-MWPooZkDfRh_ZpbVrbq:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate/blob/fe0cf285af8a945caa03b30c45d3ecce0ebae7c9/dxapp.json#L41)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
>       "help": ""
> ```
Could we add a short description of the output files to each of the help fields?
</blockquote></details>

Done.
___
*[README.md, line 11 at r3](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate/1#-MVUs0vT4CMsYhwRU2la:-MWPosqM4cMI7rOSoaum:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate/blob/fe0cf285af8a945caa03b30c45d3ecce0ebae7c9/README.md#L11)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Could we describe where these come from (i.e. extract)
</blockquote></details>

Done.
___
*[README.md, line 17 at r3](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate/1#-MVUsjAPA3aHsokZmsvU:-MWPovk-3HPckcxB_ZTP:bnajndm) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate/blob/fe0cf285af8a945caa03b30c45d3ecce0ebae7c9/README.md#L17)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> Text File which contains prefix for outputs, can be run folder here ideally, default is somalier prefix. (Optional)·
> ```
Does this need to be a file rather than a string containing the prefix? There may be a good reason for doing this in the way you have done it, but if so it would be useful to explain this
</blockquote></details>

Done. Changed to filename string rather than txt input. I thought it's better to store in file than typing it out everytime but I think there maybe a config file or something similar for workflows to add the string prefix into the app
___
*[README.md, line 30 at r3](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate/1#-MVUt5FD0GcD8JJAmhOm:-MWPpTUy8LZgsfC1IkaC:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate/blob/fe0cf285af8a945caa03b30c45d3ecce0ebae7c9/README.md#L30)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> a multi workflow as the app can take multiple inputs in.
> ```
a multi sample workflow
</blockquote></details>

Done.
___
*[README.md, line 34 at r3](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate/1#-MVUtK9X-dA861K3ViOz:-MWPpVvc8eRBU-IJOhLE:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate/blob/fe0cf285af8a945caa03b30c45d3ecce0ebae7c9/README.md#L34)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> Males typically have 0 or 1 het calls whereas female have a wider range, typically starting at 45.
> ```
Exact numbers will depend on the assay, I would describe this in more abstract terms rather than giving specific numbers
</blockquote></details>

Done.
___
*[resources/home/dnanexus/make_ped.py, line 72 at r3](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate/1#-MVkN9sk-8esKWqQ4JcA:-MWPpY4VDCPxLjSKOuVM:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate/blob/fe0cf285af8a945caa03b30c45d3ecce0ebae7c9/resources/home/dnanexus/make_ped.py#L72)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Could we add a comment here to explain that you are preparing arrays of values for each of the fields in the df?
</blockquote></details>

Done.
___
*[src/eggd_somalier_relate.sh, line 9 at r3](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate/1#-MVkNdaB93cBiLpQ6dTq:-MWPpZhq75YEmt1CnNiY:betyblc) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate/blob/fe0cf285af8a945caa03b30c45d3ecce0ebae7c9/src/eggd_somalier_relate.sh#L9)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
>     echo "Value of female: '${f}'"
>     echo "Value of male: '${m}'"
> ```
female threshold
male threshold

might be clearer
</blockquote></details>

Removed this for this app but included feedback on relate2multiqc
___
*[src/eggd_somalier_relate.sh, line 16 at r3](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate/1#-MVkNqeMDChZInbwRAcx:-MWPpw-JBNEUMqjJuSrE:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate/blob/fe0cf285af8a945caa03b30c45d3ecce0ebae7c9/src/eggd_somalier_relate.sh#L16)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> find ~/in -type f -name "*" -print0 | xargs -0 -I {} mv {} ./
> ```
Add a comment to explain this line please
</blockquote></details>

Done.

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate/1)* status: all files reviewed, 1 unresolved discussion (waiting on @Aisha-D)

___
*[README.md, line 4 at r3](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate/1#-MVUrhsE1n71qjxsUrkx:-MWTINwq-J-ecwc7akzI:bmjjcub) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate/blob/fe0cf285af8a945caa03b30c45d3ecce0ebae7c9/README.md#L4)):*
> ```
> os
> ```
Typo

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate/1)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @mattgarner)

___
*[README.md, line 4 at r3](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate/1#-MVUrhsE1n71qjxsUrkx:-MWTUA_RAy9iY0jkDKm7:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate/blob/fe0cf285af8a945caa03b30c45d3ecce0ebae7c9/README.md#L4)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> os
> ```
Typo
</blockquote></details>

Done.

**Review by mattgarner — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Aisha-D)

**Pull request merged**
