### PR TITLE
Di 133 update4epic

### PR DESCRIPTION
**Pull request by Addy81**
Update to remove EGG code dependency within sample names.

Changes:
* re.search logic changed to remove EGG dependency
* updated app to 20.04 ubuntu and updated fields to meet newer spec
* updated python packages required
* added docker image as an input instead of hardcoded file-ids
* updated readme

I can now be run and pulled through into MultiQC correctly - 
image

Jobs to show this works:
* Updated app - https://platform.dnanexus.com/projects/GP7pQ704Qz8gKf717GyQgXf7/monitor/job/GP8Xjx04Qz8ZyJBZVbGXxFgj
* Run through relate2multiqc - https://platform.dnanexus.com/projects/GP7pQ704Qz8gKf717GyQgXf7/monitor/job/GP8Z6k04Qz8y53QFY91QJqb9
* Multiqc job above screenshot came from - https://platform.dnanexus.com/projects/GP7pQ704Qz8gKf717GyQgXf7/monitor/job/GP8ZFV04Qz8bY6bV9Yg855G3

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate/10)

### CODE REVIEW

**Review by Aisha-D — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate/10)* status: 0 of 12 files reviewed, 1 unresolved discussion (waiting on @Addy81)

___
*[`src/eggd_somalier_relate.sh` line 9 at r1](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate/10#-NMdnVtm09AJF9q8rnKq:-NMdnVtm09AJF9q8rnKr:b-jt9d1f) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate/blob/aa090c8152c67a20ed47a7a6b151129c656b531b/src/eggd_somalier_relate.sh#L9)):*
> ```Shell
>     # Install packages
>     export PATH=$PATH:/home/dnanexus/.local/bin  # pip installs some packages here, add to path
>     sudo -H python3 -m pip install --no-index --no-deps packages/*
> ```

there's a python package that can be used on DNAnexus so we dont have to maintain packages. its at 001_reference:/app_assets/python_packages/python_packages_v1.1.0

**Review by Aisha-D — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate/10)* status: 0 of 12 files reviewed, 2 unresolved discussions (waiting on @Addy81)

___
*[`resources/home/dnanexus/make_ped.py` line 70 at r1](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate/10#-NMdoHSF4apDu7S4P5_6:-NMdoHSF4apDu7S4P5_7:bqigdrk) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate/blob/aa090c8152c67a20ed47a7a6b151129c656b531b/resources/home/dnanexus/make_ped.py#L70)):*
> ```Python
>         match = re.search(sex_pattern, sample)
>         if match:
>             sex_char = match.group(0)
> ```

why was the if statement removed?

**Review by Aisha-D — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate/10)* status: 0 of 12 files reviewed, 3 unresolved discussions (waiting on @Addy81)

___
*[`README.md` line 8 at r1](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate/10#-NMdoRTN3Nd5zB-n_72H:-NMdoRTN3Nd5zB-n_72I:bmxiru) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate/blob/aa090c8152c67a20ed47a7a6b151129c656b531b/README.md#L8)):*
> ```Markdown
> This app is based on https://github.com/brentp/somalier
> 
> Image of workflow
> ```

the workflow needs updating too

**Review by Addy81 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate/10)* status: 0 of 12 files reviewed, 3 unresolved discussions (waiting on @Aisha-D)

___
*[`resources/home/dnanexus/make_ped.py` line 70 at r1](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate/10#-NMdoHSF4apDu7S4P5_6:-NMdo_ckBbDDW-pdVuOk:b-b8o9av) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate/blob/aa090c8152c67a20ed47a7a6b151129c656b531b/resources/home/dnanexus/make_ped.py#L70)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

why was the if statement removed?
</blockquote></details>

There's discussions about having other single character fields to denote DNA/RNA or specimen type and those missing will also match with that if statement. Decision to remove it was agreed and if there's no FUNM characters it should be caught with the else statement.
___
*[`src/eggd_somalier_relate.sh` line 9 at r1](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate/10#-NMdnVtm09AJF9q8rnKq:-NMdosupCJc373Vb4TIU:b2qgfo2) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate/blob/aa090c8152c67a20ed47a7a6b151129c656b531b/src/eggd_somalier_relate.sh#L9)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

there's a python package that can be used on DNAnexus so we dont have to maintain packages. its at 001_reference:/app_assets/python_packages/python_packages_v1.1.0
</blockquote></details>

Those packages haven't been updated since 2021. Not sure if they have been tested for 20.04, the ones included with somalier failed cause incompatible.

**Review by Aisha-D — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate/10)* status: 0 of 12 files reviewed, 3 unresolved discussions (waiting on @Addy81)

___
*[`src/eggd_somalier_relate.sh` line 9 at r1](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate/10#-NMdnVtm09AJF9q8rnKq:-NMdqHhS7Nchrsem-hD4:bnnj06x) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate/blob/aa090c8152c67a20ed47a7a6b151129c656b531b/src/eggd_somalier_relate.sh#L9)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

Those packages haven't been updated since 2021. Not sure if they have been tested for 20.04, the ones included with somalier failed cause incompatible.
</blockquote></details>

I've used it in an applet that 20.04. The fact that it hasn't been updated since is an issue (sounds like something the QE team could do). Its fine youve updated it then

**Review by Aisha-D — COMMENTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate/10)* status: all files reviewed, 1 unresolved discussion (waiting on @Addy81)

**Review by Aisha-D — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate/10)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Addy81)

**Pull request merged**
